# Fireball block damage
# Made by RedW0lfStoneYT
# version 0.7

vanillaBlocks: false  # set to false to just allow fireballs to break the items on the breakable list rather then the vanilla ones as well 
blocks:
   breakable: 
      '0': 
         type: 1   # Stone and other stone variants stone:1 stone:2 (granite and polishedgranite) ect 
      '1': 
         type: 2   # Grass
      '2':
         type: 3   # Dirt, podzol & Coarse Dirt
      '3':
         type: 4   # Cobble
      '4':
         type: 52  # Spawner 
