name: addEnchant
author: RedW0lfStoneYT
main: me.redw0lfstone.addEnchant.main
version: 0.8
depend: [Vault, Essentials]
commands: 
   addEnchant:
      usage: /<command> ENCHANT LEVEL
   buyEnchant:
      usage: /<command> ENCHANT LEVEL
   